---
title: "German Willkommenskultur"
author: "Christopher Cosler and Lisa Schmid"
date: "December 4, 2015"
output:
  revealjs::revealjs_presentation:
    theme: sky
    transition: fade
    highlight: pygments
    center: true
---

```{r, include = FALSE}
# Load source file
source("Analysis/Analysis.R")
# Load libraries for presentation
```

# Introduction

# Data sources
1. *ProAsyl map* ^[https://www.google.com/maps/d/viewer?mid=zc6TdvfelKuY.kUvriXoSREXw]
2. *German Federal Agency for Cartography and Geodesy* ^[http://www.geodatenzentrum.de/geodaten/gdz_rahmen.gdz_div?gdz_spr=deu&gdz_akt_zeile=5&gdz_anz_zeile=1&gdz_unt_zeile=19&gdz_user_id=0]
3. *German Federal Statistical Office* ^[https://www-genesis.destatis.de/genesis/online]
4. *German Regional Statistical Offices* ^[https://www.regionalstatistik.de/genesis/online]

# Dependent variable
```{r, echo=FALSE, fig.align='center', fig.cap="Histogram of refugee", fig.width=5, fig.height=5}
plot(histogram)
```

# East-West 
```{r, echo=FALSE, fig.align='center', fig.cap="Histogram of refugee", fig.width=5, fig.height=5}
plot_eastwest
```

# Age
```{r, echo=FALSE, fig.align='center', fig.cap="Histogram of refugee", fig.width=5, fig.height=5}
plot_age_eastwest
```

# GDP per capita
```{r, echo=FALSE, fig.align='center', fig.cap="Histogram of refugee", fig.width=5, fig.height=5}
plot_GDP_eastwest
```

# Gender 
```{r, echo=FALSE, fig.align='center', fig.cap="Histogram of refugee", fig.width=5, fig.height=5}
plot_gender_eastwest
```

# Turnout
```{r, echo=FALSE, fig.align='center', fig.cap="Histogram of refugee", fig.width=5, fig.height=5}
plot_turnout_eastwest
```

# East West Germany Map
```{r, echo=FALSE, fig.align='center', fig.cap="Histogram of refugee", fig.width=5, fig.height=5}
# Cut data into classes
classes <- cut(Data.fin$east, c(0, 1), right = FALSE)
levels(classes) <- c("West", "East")
# Assign colors
colours <- c("black", "white") # Pick color palette
# Plot shapefile colored
plot(Shapes_krs,border = "darkgrey", col = colours[classes])
# Add legend
levels <- c("0<0.25", "0.25<0.3", "0.3<0.4", "0.4<0.45", "0.45<0.5")
legend("right", fill = colours, legend = levels)
```

# East West Germany Map
```{r, echo=FALSE, fig.align='center', fig.cap="Histogram of refugee", fig.width=5, fig.height=5}
# Cut data into classes
classes <- cut(Data.fin$east, c(0, 1), right = FALSE)
levels(classes) <- c("West", "East")
# Assign colors
colours <- c("black", "white") # Pick color palette
# Plot shapefile colored
plot(Shapes_krs,border = "darkgrey", col = colours[classes])
# Add legend
levels <- c("West", "East")
legend("right", fill = colours, legend = levels)
points(Coordinates$Longitude, Coordinates$Latitude, col = adjustcolor("red",0.4),pch = 19)
```

# Age Map
```{r, echo=FALSE, fig.align='center', fig.cap="Histogram of refugee", fig.width=5, fig.height=5}
# Cut data into classes
classes <- cut(Data.fin$oldage.dependency, c(0.25, 0.3, 0.35, 0.4, 0.45, 0.5), right = FALSE)
levels(classes) <- c("<0.25", "<0.3", "<0.4", "<0.45", "<0.5")
# Assign colors
colours <- brewer.pal(6,"BuGn") # Pick color palette
# Plot shapefile colored
plot(Shapes_krs,border = "darkgrey", col = colours[classes])
# Add legend
levels <- c("<0.25", "<0.3", "<0.4", "<0.45", "<0.5")
legend("right", fill = colours, legend = levels)
```

# Age Map
```{r, echo=FALSE, fig.align='center', fig.cap="Histogram of refugee", fig.width=5, fig.height=5}
# Cut data into classes
classes <- cut(Data.fin$oldage.dependency, c(0.25, 0.3, 0.35, 0.4, 0.45, 0.5), right = FALSE)
levels(classes) <- c("0<0.25", "0.25<0.3", "0.3<0.4", "0.4<0.45", "0.45<0.5")
# Assign colors
colours <- brewer.pal(6,"BuGn") # Pick color palette
# Plot shapefile colored
plot(Shapes_krs,border = "darkgrey", col = colours[classes])
points(Coordinates$Longitude, Coordinates$Latitude, col = adjustcolor("red",0.4),pch = 19)
# Add legend
levels <- c("<0.25", "<0.3", "<0.4", "<0.45", "<0.5")
legend("right", fill = colours, legend = levels)
```

# Turnout Map
```{r, echo=FALSE, fig.align='center', fig.cap="Histogram of refugee", fig.width=5, fig.height=5}
# Cut data into classes
classes <- cut(Data.fin$turnout, c(60, 63, 65, 68, 70, 73, 76), right = FALSE)
levels(classes) <- c("60", "63", "65", "68", "70", "73", "76")
# Assign colors
colours <- brewer.pal(8,"BuGn") # Pick color palette
# Plot shapefile colored
plot(Shapes_krs,border = "darkgrey", col = colours[classes])
# Add legend
levels <- c("60", "63", "65", "68", "70", "73", "76")
legend("right", fill = colours, legend = levels)
```

# Turnout Map
```{r, echo=FALSE, fig.align='center', fig.cap="Histogram of refugee", fig.width=5, fig.height=5}
# Cut data into classes
classes <- cut(Data.fin$turnout, c(60, 63, 65, 68, 70, 73, 76), right = FALSE)
levels(classes) <- c("60", "63", "65", "68", "70", "73", "76")
# Assign colors
colours <- brewer.pal(8,"BuGn") # Pick color palette
# Plot shapefile colored
plot(Shapes_krs,border = "darkgrey", col = colours[classes])
# Add legend
levels <- c("60", "63", "65", "68", "70", "73", "76")
legend("right", fill = colours, legend = levels)
points(Coordinates$Longitude, Coordinates$Latitude, col = adjustcolor("red",0.4),pch = 19)
```